version: '3'

#Docker Networks
networks:
  app-network:
    driver: bridge

services:
  #PHP Service
  php:
    container_name: sk_php
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  nginx:
    container_name: sk_nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - app-network

  #Redis Service
  redis:
    container_name: sk_redis
    image: redis:alpine
    ports:
     - "6379:6379"
    networks:
     - app-network
